name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v3
    
    - name: 设置 Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: 安装依赖
      working-directory: ./thchat-ui
      run: npm install
      
    - name: 构建项目
      working-directory: ./thchat-ui
      run: npm run build
      
    - name: 部署
      uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: ./thchat-ui/dist